"""Update user model for secure password encryption

Revision ID: 7a4b0f1c6214
Revises: 
Create Date: 2025-07-30 20:59:37.468632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4b0f1c6214'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_password', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('indeed_password', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('naukri_password', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('internshala_password', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.drop_column('indeed_password_hash')
        batch_op.drop_column('internshala_password_hash')
        batch_op.drop_column('linkedin_password_hash')
        batch_op.drop_column('naukri_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('naukri_password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('linkedin_password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('internshala_password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('indeed_password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('internshala_password')
        batch_op.drop_column('naukri_password')
        batch_op.drop_column('indeed_password')
        batch_op.drop_column('linkedin_password')

    # ### end Alembic commands ###
